backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "poems"
    label: "Poems"
    folder: "poems"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Thoughts", name: "thoughts", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
